---
kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: golang:1.21.0
  volumes:
  - name: deps
    path: /go
  commands:
  - go test -v
  - go build

- name: docker
  image: harbor.ntppool.org/ntppool/drone-kaniko:main
  pull: always
  volumes:
  - name: deps
    path: /go
  settings:
    repo: library/locationcode
    registry: harbor.ntppool.org
    auto_tag: true
    tags: SHA7,${DRONE_SOURCE_BRANCH}
    cache: true
    username:
      from_secret: harbor_library_username
    password:
      from_secret: harbor_library_password    
---
kind: signature
hmac: 454d074a3b5f6d2400872f4d2c1b368b66f0243a398fa13423d3b904a865fedc

...
