---
kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: golang:1.23.4
  volumes:
  - name: deps
    path: /go
  commands:
  - go test -v
  - go build

- name: docker
  image: harbor.ntppool.org/ntppool/drone-kaniko:main
  pull: always
  volumes:
  - name: deps
    path: /go
  settings:
    repo: library/locationcode
    registry: harbor.ntppool.org
    auto_tag: true
    tags: SHA7,${DRONE_SOURCE_BRANCH}
    cache: true
    username:
      from_secret: harbor_library_username
    password:
      from_secret: harbor_library_password    
---
kind: signature
hmac: 414d7d025564e4b76e058d81a381ca6091289e8b5560da07ea98563cb647f19f

...
